const actionTypes= {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
    GET_NEW_POSTS: 'GET_NEW_POSTS',

    GET_CATEGORIES:'GET_CATEGORIES',
    GET_PRICES:'GET_PRICES',
    GET_AREAS:'GET_AREAS',
}
export default actionTypes